
worker_processes  1;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    client_max_body_size 0;
    sendfile        on;
    keepalive_timeout  65;
  
	server {
        listen       24000;
        server_name  metroDas;
        location / {
            root   /workspace/MAIN/web;
            add_header Access-Control-Allow-Origin *;
			add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
			add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
        location /webApi/ {
            proxy_pass http://127.0.0.1:8000;
            proxy_http_version 1.1; # 使用HTTP/1.1以支持长连接
			proxy_set_header Upgrade $http_upgrade; # 用于Websocket和SSE的Upgrade头
			proxy_set_header Connection "upgrade"; # 设置Connection头为upgrade，维持长连接
			proxy_set_header Host $host; # 传递原始Host头给后端
			proxy_cache_bypass $http_upgrade; # 忽略缓存，对于实时连接很重要

             # 设置超时时间
            proxy_read_timeout 86400s;  # 读取超时时间为秒
            proxy_connect_timeout 86400s; # 连接超时时间为秒
            proxy_send_timeout 86400s;    # 发送请求超时时间为秒

            proxy_buffer_size 16k; 
            proxy_buffers 4 64k; 
            proxy_busy_buffers_size 128k; 
            proxy_temp_file_write_size 128k;

            # 取消缓冲
            proxy_buffering off;

			# 关闭代理缓存
            proxy_cache off;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
		}
    }
}

